// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBBDLbVYwnRxmYxvGOYya_1hDkPJuE42k',
    appId: '1:63607570553:web:d178a7cb6d0bf90235d4a8',
    messagingSenderId: '63607570553',
    projectId: 'authentication-7d188',
    authDomain: 'authentication-7d188.firebaseapp.com',
    storageBucket: 'authentication-7d188.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1LZEIW4t-97hWA2zRSiLKJa0vyzaKJpI',
    appId: '1:63607570553:android:a21c28ac3a49ebed35d4a8',
    messagingSenderId: '63607570553',
    projectId: 'authentication-7d188',
    storageBucket: 'authentication-7d188.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMi8DKZ6CCpnBfO_-OOkME0UYrzsGAYeE',
    appId: '1:63607570553:ios:ae889e9d4d35b9d435d4a8',
    messagingSenderId: '63607570553',
    projectId: 'authentication-7d188',
    storageBucket: 'authentication-7d188.appspot.com',
    iosBundleId: 'com.example.authxfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMi8DKZ6CCpnBfO_-OOkME0UYrzsGAYeE',
    appId: '1:63607570553:ios:ae889e9d4d35b9d435d4a8',
    messagingSenderId: '63607570553',
    projectId: 'authentication-7d188',
    storageBucket: 'authentication-7d188.appspot.com',
    iosBundleId: 'com.example.authxfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBBDLbVYwnRxmYxvGOYya_1hDkPJuE42k',
    appId: '1:63607570553:web:42a52739ff3d2b6d35d4a8',
    messagingSenderId: '63607570553',
    projectId: 'authentication-7d188',
    authDomain: 'authentication-7d188.firebaseapp.com',
    storageBucket: 'authentication-7d188.appspot.com',
  );
}
